"""Application configuration read from the environment / a local .env file.

All settings have safe local defaults (see ``.env.example``); nothing here is
secret. ``SECRET_KEY`` falls back to a per-process random value when omitted,
and ``BUILD_MARKER`` falls back to the ``VERSION`` file generated by
``scripts/build.sh``.
"""

import os
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_DB_PATH = BASE_DIR / "data" / "taskboard.db"


class Settings(BaseSettings):
    """Runtime configuration. Field names map to UPPER_CASE environment
    variables (pydantic-settings matches case-insensitively)."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    app_name: str = "deploy-test-fastapi"
    environment: str = "development"

    # Bind address / port for the ASGI process.
    host: str = "0.0.0.0"
    port: int = 8000

    # Persistent SQLite file. For real deployments point this at storage
    # OUTSIDE the checkout (a mounted volume), otherwise data is lost on
    # redeploy:  /var/lib/taskboard/taskboard.db
    database_path: str = str(DEFAULT_DB_PATH)

    # Random signing key used for the signed session cookie (which backs
    # CSRF tokens). Generate once and keep stable across restarts.
    secret_key: str = ""

    # Optional non-sensitive marker shown in the UI footer identifying the
    # deployed revision. Defaults to the VERSION file at the repo root.
    build_marker: str = ""

    log_level: str = "info"

    max_content_length: int = 1_000_000

    @property
    def resolved_database_path(self) -> str:
        """Expand environment variables and ~ in the configured DB path."""
        return os.path.expandvars(os.path.expanduser(self.database_path))

    @property
    def database_path_is_default(self) -> bool:
        """True when DATABASE_PATH was not provided explicitly."""
        return "database_path" not in self.model_fields_set


def get_settings() -> Settings:
    """Return fresh settings; pydantic-settings caches nothing itself."""
    return Settings()
